### ISSUE TITLE
NPM install reference to ssh://git@github.com/zeplin/eslint-config-zeplin.git

### ISSUE THREAD

**Issue by er1c** [zeplin/zeplin-html-to-pdf#12]
I believe `https://github.com/zeplin/eslint-config-zeplin.git` was renamed to `https://github.com/zeplin/eslint-config.git`

`package.json`: "eslint-config-zeplin": "git+ssh://git@github.com/zeplin/eslint-config-zeplin.git#v1.x.x"

```
21 verbose stack Error: exited with error code: 128
21 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
21 verbose stack     at ChildProcess.emit (events.js:182:13)
21 verbose stack     at maybeClose (internal/child_process.js:962:16)
21 verbose stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
21 verbose stack     at Socket.emit (events.js:182:13)
21 verbose stack     at Pipe._handle.close (net.js:606:12)
22 verbose cwd /Users/eric/Work/zeplin-html-to-pdf
23 verbose Darwin 17.7.0
24 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
25 verbose node v10.13.0
26 verbose npm  v6.4.1
27 error Error while executing:
27 error /usr/bin/git ls-remote -h -t ssh://git@github.com/zeplin/eslint-config-zeplin.git
27 error
27 error git@github.com: Permission denied (publickey).
27 error fatal: Could not read from remote repository.
27 error
27 error Please make sure you have the correct access rights
27 error and the repository exists.
27 error
27 error exited with error code: 128
28 verbose exit [ 1, true ]
```

**Comment by dirtybit** [comment]
@er1c Thanks for reporting this! It's been fixed now.
