### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by GozPaez** [zeplin/zeplin-html-to-pdf#18]
When I tested with the string recommended, receive the following message: 

{
  "errorMessage": "Cannot find module '/var/task/index'",
  "errorType": "Error",
  "stackTrace": [
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)"
  ]
}

**Comment by aviban** [comment]
Hi, I am receiving an error:

2020-02-07T13:56:27.191Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'index'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'index'",
        "Require stack:",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:956:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)",
        "    at Module.load (internal/modules/cjs/loader.js:812:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)",
        "    at internal/main/run_main_module.js:17:11"
    ]
}

Can you please help me in resolving the same,

**Comment by dorukgunes** [comment]
@aviban @GozPaez What is the runtime are you trying to run this function? If you are using a runtime >=nodejs6.10 please try again since we released a major update and make sure you pull the latest version this repository.
