### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by gduggirala** [zeplin/zeplin-html-to-pdf#3]
When I am testing on my local machine I am getting the following error.
Any clue how this can be resolved?

````
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:911:11)
    at WriteWrap.afterWrite (net.js:785:14)
````

The following is the command 

`node ./local/index.js ../test.html test.pdf`

**Comment by dirtybit** [comment]
The reason is you don't have `wkhtmltopdf` executable in your `PATH`, so the script tries to use the one in this repository. `wkhtmltopdf` in this repo is compatible with the AWS Lambda runtime (static linux-x86-64 build).

Once you install wkhtmltopdf and have it in `PATH`, it should work.

**Comment by gduggirala** [comment]
Thank you for response.. I did what you have suggested but I still get the same error... here are some logs..

```
which wkhtmltopdf
/usr/bin/wkhtmltopdf
```
And the console path when I printed this is the O/P

`/home/xxxxx/jdk1.8.0_102/bin:/home/xxxxx/Android/Sdk/tools:/home/xxxx/jdk1.8.0_102/bin:/home/xxxx/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:911:11)
    at WriteWrap.afterWrite (net.js:785:14)
```

**Comment by biswarupchakravarty** [comment]
@gduggirala I managed to get around it by downloading a latest copy of `wkhtmltopdf` (the 64bit Linux version) from [their downloads page](https://wkhtmltopdf.org/downloads.html). 

I also went from [changed this line](https://github.com/zeplin/zeplin-html-to-pdf/blob/develop/utils/wkhtmltopdf.js#L8) to read `var proc = spawn("/bin/sh", ["-o", "pipefail", "-c", "./wkhtmltopdf - - " + options.join(" ") + " | cat"]);`, thereby just reading the local copy of the file.

**Comment by dorukgunes** [comment]
I am closing this issue due to inactivity, we also released a major update, feel free to reopen the issue if you encounter this problem again.
